config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#home'

  #STATIC
  get 'history' => "welcome#history", as: :history
  get 'confirmation' => "welcome#confirmation", as: :confirmation
  get 'ethos' => "welcome#ethos", as: :ethos
  get 'locations' => "welcome#locations", as: :locations
  get 'timetable' => "welcome#timetable", as: :timetable

  #APPLICATIONS
  get 'applications' => "applications#index", as: :applications
  get 'applications/new' => "applications#new", as: :new_application
  get 'applications/:id' => "applications#show", as: :application
  post 'applications' => "applications#create"


end

app/models/application.rb
class Application < ActiveRecord::Base
	validates :email, presence: true
	validates :telephone, presence: true
	validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @applications = Application.all
  end

  def new
  	@application = Application.new
  end

  def create
  	@application = Application.new(application_params)
  	if @application.save
  		redirect_to confirmation_path, notice: 'Thank you for applying, you will be contacted shorlty'
  	else 
  		render :new
  	end
  end

  def show
  end

  def delete
  end

  private
  def application_params
  	params.require(:application).permit(:parent_first_name, :parent_last_name, :email, :telephone, :child_first_name, :child_dob, :school, :child_class, :dance_level, :location)
  	
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end

	def history	
	end

	def ethos
	end

	def locations	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/index.html.erb
<table class="table table-striped">
	<tr class="active">
		<td><h4>Parent Full Name</h4></td>
		<td><h4>Child Name</h4></td>
		<td><h4>Email</h4></td>
		<td><h4>Telephone</h4></td>
		<td><h4>Preferred location</h4></td>
		<td><h4>Date of Birth </h4></td>
		<td><h4>Dance Level</h4></td>
		<td><h4>Time/Date of application</h4></td>
	</tr>
	<% @applications.each do |app| %>
	<tr>
		<td><%= app.parent_first_name %> </td>
		<td><%= app.child_first_name %></td>
		<td><%= app.email %></td>
		<td><%= app.telephone %></td>
		<td><%= app.location %></td>
		<td><%= app.child_dob %></td>
		<td><%= app.dance_level %></td>
		<td><%= app.created_at %></td>
	</tr>
	<% end %>
</table>

app/views/applications/new.html.erb
<div class="second-container">
	<h1>Application Form</h1>
	<p> Please take a moment to complete the form below. During term time we <span>try</span> to respond to everyone within 24 hours. </p>
	<p> The information that you provide in the form below <span>will not be kept on record</span> unless you choose to fully enroll your child.</p>
	<hr>
	<div class="row">
	<%= form_for(@application) do |f| %>
	  <% if @application.errors.any? %>
	    <div id="error_explanation">
	      <h4><%= pluralize(@application.errors.count, "error") %> prohibited this application from being sent:</h4>

	      <ul>
	      <% @application.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	    <hr>
	  <% end %>
	</div>

	<div class="row">
		<div class="">
		  <div class="field form-group">
		    <%= f.label "parent name" %>
		    <%= f.text_field :parent_first_name, :class => "form-control" %>
		  </div>
		  <div class="field form-group">
		    <%= f.label "child name" %>
		    <%= f.text_field :child_first_name, :class => "form-control" %>
		  </div>
		  <div class="field form-group">
		    <%= f.label :email %>
		    <%= f.text_field :email, :class => "form-control", :placeholder => "*required" %>
		  </div>
		    <div class="field form-group">
		    <%= f.label :telephone %>
		    <%= f.text_field :telephone, :class => "form-control", :placeholder => "*required" %>
		  </div>
		  

			<div class="field form-group">
		    <%= f.label "preferred location for dance classes" %><br>
		    <%= f.select :location, options_for_select([["  *required (select from drop-down)", ""], "", "No preference", "South Kensington", "Bousfield", "Oratory", "Our Lady of Victories", "Parsons Green", "Chelsea Theatre", "Fulham Prep"]), :class => "form-control"%>
		  </div>
		  <div class="field form-group">
		    <%= f.label "child date of birth" %>
		    <%= f.text_field :child_dob, :class => "form-control", :placeholder => "DD/MM/YYYY" %>
		  </div>
		  <div class="field form-group">
		    <%= f.label "dance level (if applicable)" %>
		    <%= f.text_field :dance_level, :class => "form-control", :placeholder => "(previous experience, dance exams taken, results)" %>
		  </div>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="actions" style= "text-align:center;">
		  <%= f.submit "Apply", :class => "btn btn-primary btn-lg" %>
		</div>
	</div>

	<% end %>
</div>

app/views/applications/show.html.erb
<h1>Applications#show</h1>
<p>Find me in app/views/applications/show.html.erb</p>

app/views/layouts/_nav.html.erb
<script>
  //nav hover dropdown
    $(function() {
        $(".dropdown").hover(
            function(){ $(this).addClass('open') },
            function(){ $(this).removeClass('open') }
        );
    });
</script>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">La Sylvaine</a>
    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About</a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Ethos', ethos_path %></li>
            <li><%= link_to 'History', history_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">La Sylvaine Staff</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">News</a></li>
          </ul>
        </li>

        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Classes</a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Locations', locations_path, 'data-no-turbolink' => true %></li>
            <li><%= link_to 'Timetable', timetable_path, 'data-no-turbolink' => true %></li>
            <li><a href="#">Calendar</a></li>
            <li><a href="#">Fees</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Registration Form</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Print Outs</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Uniform</a>
          <ul class="dropdown-menu">
            <li><a href="#">Girls</a></li>
            <li><a href="#">Boys</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">BUY ONLINE</a></li>
          </ul>
        </li>

        <li><a href="#" class="dropdown-toggle">Contact</a></li>

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
       
        <form class="navbar-form navbar-left" role="search">
        <!-- <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div> -->
        <!-- <button type="submit" class="btn btn-success enroll">Enroll</button> -->
        <%= link_to 'Application Form', new_application_path, :class => "btn btn-default enroll" %>
      </form>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaSylvaine</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>--> 
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	

</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">
	<!-- <div class="second-container"> -->
		<%= yield %>
	<!-- </div> -->
</div>


</body>
</html>

app/views/welcome/confirmation.html.erb
<div class="second-container">
	<h2>Thank you for your request. </h2>

	<p>During term time we <span>try</span> to respond to everyone within 24 hours to discuss the enrollment, suitable classes and timetable
	</p>

	<%= link_to "To Home Page", root_path, :class => "btn btn-primary btn-lg" %>
</div>

app/views/welcome/ethos.html.erb
<div class="second-container">
	<h1>Ethos</h1>

	<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</p>

</div>

app/views/welcome/history.html.erb
<div class="second-container">
	<h1> History of La Sylvaine </h1>

	<p>Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,</p>
</div>

app/views/welcome/home.html.erb
<div class="second-container">

	<h1>Home</h1>

	<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</p>

	<p>Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,</p>
</div>

app/views/welcome/locations.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div class="second-container">
  <h1>Locations</h1>

  <div class="main-map">
  	<div>
  		<div id="sidebar_builder"></div>
      <br><br>
      <h5>Click links or markers for more information</h5>
  		<div id="sidebar_container" style="display:inline-block;"></div>
  	</div>
  </div>
</div>



<script>
function createSidebarLi(json){
  return ("<li><a>" + json.name + "</a></li>");
};

function bindLiToMarker($li, marker){
  $li.on('click', function(){
    handler.getMap().setZoom(14);
    marker.setMap(handler.getMap()); //because clusterer removes map property from marker
    marker.panTo();
    google.maps.event.trigger(marker.getServiceObject(), 'click');
  })
};

function createSidebar(json_array){
  _.each(json_array, function(json){
    var $li = $( createSidebarLi(json) );
    $li.appendTo('#sidebar_container');
    bindLiToMarker($li, json.marker);
  });
};

handler = Gmaps.build('Google');
handler.buildMap({ 
  provider: {
    scrollwheel: false
  }, 
  internal: {id: 'sidebar_builder'}}, 
  function(){
  var json_array = [
    { lat: 51.4897156, lng: -0.1873473, name: 'Bousfield Primary School', infowindow: "<h4>Bousfield Primary School</h4><h5>South Bolton Gardens, London, SW5 0DJ</h5><p>Classes are on Tuesday</p>" },
    { lat: 51.4938150, lng: -0.1771200, name: 'South Kensington - Fitness First', infowindow: "<h4>Fitness First</h4><h5>Petersham House, Harrington Rd, London SW7 3HD</h5><p>Classes are on Mondays and Fridays</p>" },
    { lat: 51.4934390, lng: -0.1767410, name: 'South Kensington - Yoga Centre', infowindow: "<h4>Evolve Wellness Centre</h4><h5>10 Kendrick Mews</h5><p>Classes are on Wednesdays in Studio 1 with Miss Chloe Bergeret</p>" },
    { lat: 51.4736680, lng: -0.2007371, name: 'Wendy Bell', infowindow: "<h4>Mission Hall</h4><h5>Parsons Green Lane (corner of St Dionis Road)</h5><p> Classes are on Mondays, Tuesdays and Thursdays</p>" },
    { lat: 51.4721910, lng: -0.1909650, name: "L'Ecole des Petits", infowindow: "<h4>L'Ecole des Petits</h4><h5>2 Hazlebury Road London SW6 2NB</h5><p>Classes are on Tuesday, Wednesday and Thursday and are under the responsibility of Pascale Chambon</p>" },
    { lat: 51.4843420, lng: -0.1779640, name: "Tadpoles Nursery", infowindow: "<h4>Tadpoles Nursery</h4><h5>Park Walk Playcentre Building, Park Walk, London, SW10 0AY</h5><p>Classes are on Tuesday under the responsibility of Chloe Bergeret</p>" },
    { lat: 51.4960500, lng: -0.2189760, name: "Ecole Française Jacques Prévert", infowindow: "<h4>Ecole Française Jacques Prévert</h4><h5>59 Brook Green, London W6 7BE, United Kingdom</h5><p>Classes are on Wednesday under the responsibility of Pascale Chambon</p>" },
    { lat: 51.4862940, lng: -0.2097720, name: "Fulham Prep School", infowindow: "<h4>Fulham Prep School</h4><h5>200 Greyhound Road London W14 9SD</h5><p> Ballet and tap classes under the responsibility of Clotilde Bortz</p>" },
    { lat: 51.4902860, lng: -0.1699430, name: "The Oratory (Ballet Club)", infowindow: "<h4>Oratory Roman Catholic Primary School (Ballet Club)</h4><h5>Bury Walk, Cale Street, London SW3 6QH</h5><p>Ballet Club only (Wednesday)</p>" },
    { lat: 51.4991850, lng: -0.1976360, name: "Our Lady Of Victories (Ballet Club Only)", infowindow: "<h4>Our Lady Of Victories (Ballet Club Only)</h4><h5>235a Kensington High St, London W8 6SA</h5><p>Ballet Club only (Thursday)</p>" },
    { lat: 51.4886500, lng: -0.1903510, name: "Redcliffe School (Ballet Club Only)", infowindow: "<h4>Redcliffe School (Ballet Club Only)</h4><h5>96 Redcliffe Gardens, London, Middlesex SW10 9HH</h5><p>Ballet Club only (Thursday)</p>" },
    { lat: 51.4886500, lng: -0.1903510, name: "Chelsea Theatre", infowindow: "<h4>Chelsea Theatre</h4><h5>7 World’s End Place, King's Road, London SW10 0DR</h5><p>Classes for all ages and levels on Saturday mornings</p>" }

  ];


  var markers = handler.addMarkers(json_array);

  _.each(json_array, function(json, index){
    json.marker = markers[index];
  });

  createSidebar(json_array);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
    

</script>

app/views/welcome/timetable.html.erb
<div class="second-container">
	<h1>ACADEMIC YEAR 2015 – 2016</h1>
	<p> Ballet clubs are open to children from the named academic school only.</p>
	
	<p>*Indicates  an  exam  class. Children  are  expected  to  come  twice  a  week  if  wanting  to  take  a  ballet  exam </p>	
	<hr>
	<h3>MONDAY</h3>	
	<h4>SOUTH KENSINGTON STUDIO</h4>
	<h5>Fitness First - Harrington Road, SW7</h5>
	<ul>
		<li>3.50 — 4.45 Grade 2 Level 2 Exam Class (CM1/ CM2)</li>
		<li>4.50 — 5.50 Grade 4 Level 1 (CM2/ 6e)</li>
	</ul>
	<h4>WENDY BELL</h4>
	<h5>Mission Hall Downstairs - Parsons Green Lane (corner of St Dionis Road)</h5>
	<ul>
		<li>4.00 — 4.40 Introduction (2 & 3 years old)</li>
		<li>4.45 — 5.45 Grade 2 Level 2  Exam  Class  *</li>
	</ul>
	<h4>WENDY BELL</h4>
	<h5>Mission Hall Upstairs - Parsons Green Lane (corner of St Dionis Road)</h5>
	<ul>
		<li>4.00 — 4.45 Pre‐primary (4 & 5  years  old)</li>
		<li>4.55 — 5.50 Grade 2 Level 1 (8+ years old)</li>
		<li>    5.55 — 6.55 Grade 4 (*)</li>
		<li>6.55 — 8.00 Grade 7 (*)</li>
	</ul>
	

	<hr>
	<h3>TUESDAY</h3>
	<h4>ECOLE  DES  PETITS</h4> 
	<h5>Wandsworth/Battersea</h5>
	<ul>
		<li>Tuesday</li>
		<li>Wednesday </li>
		<li>Thursday</li>
	</ul>
	<p>Classes under the responsibility of Pascale Chambon </p>
	<h4>TADPOLE NURSERY</h4>
	<h5>Park  Walk, Chelsea</h5>
	<p>                   Classes under the responsibility of Chloé Bergeret </p>
	<h4>WENDY BELL</h4> 
	<h5>Mission Hall Upstairs - Parsons Green Lane (corner of St Dionis Road)</h5>
	<ul>
		<li>3.45 — 4.25 Primary (5&6years old)</li>
		<li>4.30 — 5.10 Grade 1 level 1 (7 years old)</li>
		<li>5.15 — 6.10 Grade 3 Level 2 (*)</li>
		<li>6.15 — 7.15 Intermediate Foundation</li>
		<li>7.15 — 8.15 Grade 6</li>
	</ul>
	<h4>BOUSFIELD SCHOOL</h4>
	<h5>South  Bolton  Gardens, Chelsea</h5>
	<ul>
		<li>3.50 — 4.30 Introduction (3 & 4 years old) </li>
		<li>3.40 — 4.30 Pre‐Primary (4 &  5  years  old) </li>
		<li>4.30 — 5.15 Grade 1 (7 years old) </li>
		<li>4.30 — 5.15 Primary (6 years old)</li>
		<li>5.15 — 6.00 Grade 2 5.15 — 6.00 Grade 3</li>
	</ul>
	

	<hr>
	<h3>WEDNESDAY</h3>
	<h4>ECOLE JACQUES PREVERT</h4>
	<h5>Brook Green,Hammersmith</h5>
	<p>    Classes under the responsibility of Pascale Chambon</p>

	<h4>SOUTH KENSINGTON STUDIO</h4> 
	<h5>Yoga Centre - 10 Kendrick Mews - Studio  1  (Chloé)</h5>
	<ul>
		<li>2.45 — 3.30 Introduction  (Mat ernelles and  new  pupils  in  CP)</li>
		<li>3.45 — 4.30 Modern Jazz HipHop 1</li>
		<li>4.40 — 5.35 Grade  3  Level  2</li>
	</ul>
	<h4>FULHAM PREP LOWER SCHOOL</h4>
	<h5>Fulham Palace Road, Fulham</h5>
	<p>Ballet and tap classes under the responsibility of Clotilde Bortz</p>
	<ul>
		<li>3.30 — 4.45 Year 1 and 2</li>
	</ul>
	<h4>THE   ORATORY (Ballet   Club Only)</h4>
	<h5>Bury Walk,  Chelsea</h5>
	<ul>
		<li>3.45 — 4.30 Infant Year R, 1</li>
		<li>4.30 — 5.15 Junior , Year  2, Year  3</li>
	</ul>


	<hr>
	<h3>THURSDAY</h3>
	<h4>OUR  LADY OF  VICTORIES (Ballet Club Only)</h4>
	<h5>South  Kensington</h5>
	<ul>
		<li>1.00 — 2.00 Nursery</li>
		<li>3.30 — 4.10 Year R</li>
		<li>4.10 — 4.50 Year 1 , Year  2  & above</li>
	</ul>

	<h4>REDCLIFFE  SCHOOL (Ballet Club Only)
	<h5>Redcliffe    Gardens, Chelsea</h5>

	<p>Robins: Monday Morning 10 am</p>
	<ul>
		<li>3.30 — 4.10 Kingfishers, Skylarks</li>
		<li>4.10 — 4.50 Bronte Coleridge</li>
	</ul>
	

	<h4>WENDY BELL</h4>
	<h5> Mission Hall Upstairs - Parsons Green Lane (corner of St Dionis Road)</h5>
	<ul>
		<li>5.30 — 6.15       Grade 4 coaching class for examinations</li>
		<li>6.15 — 7.30 Intermediate Foundation</li>
		<li>7.30 — 8.30 Grade 8</li>
	</ul>


	<hr>
	<h3>FRIDAY</h3>

	<h4>SOUTH KENSINGTON STUDIO</h4>
	<h5>Fitness First - Harrington Road, SW7</h5>
	<ul>
		<li>4.30 — 5.30 Intermediate Foundation level 1</li>
		<li>5.30  –  6.30         Intermediate  Foundation  level  2  (Exam  Class)</li>
		<li>6.30 – 7.30 Grade 6</li>
	</ul>

	<hr>
	<h3>SATURDAY</h3>

	<h4>CHELSEA THEATRE</h4>
	<h5>Worlds End Place, Kings Road</h5>
	<ul>
		<li>9.30 — 10.30 Grade 3  level  2  (Chloé) </li>
		<li>9.30 — 10.30 Grade 4  level  2  (Blandine) </li>
		<li>9.45 — 10.30    Grade  2  Exam   (Clotilde)</li>
		<li>10.30 — 11.40 Inter Foundation Exam (Pascale/Chloé)</li>
		<li>10.45 — 11.40 Grade 4  level  1 (Blandine) </li>
		<li>10.30 — 11.25 Hip Hop B (Clotilde)</li>
		<li>11.45 — 12.55 Inter Foundation Level 1 (Chloé) </li>
		<li>11.45 — 12.55 Grade  6   (Pascale/Blandine) </li>
		<li>11.50 — 12.45 Hip Hop Senior (Clotilde)</li>
	</ul>
</div>